### ISSUE TITLE
Example App Window Flickers on Launch, becomes unresponsive.

### ISSUE THREAD

**Issue by stemcc** [bengotow/electron-RxDB#1]
- OS Version: macOS 10.12.1

Steps to Reproduce:

1. Install library as indicated.
2. Install example app, then `npm run`

App launches and remains in an unresponsive state.

**Comment by bengotow** [comment]
Hey @stemcc thanks for reporting this on Slack earlier - I was able to reproduce this on my machine, could you try pulling down `master` again and let me know if you still have trouble? You may need to delete the database file in `~/Library/Application Support/Notes` - I also added FTS5 search to the example app!

**Comment by stemcc** [comment]
@bengotow Example app works great now. Tested and works with Electron 1.4.10. 

Closing the issue.
